### ISSUE TITLE
Crash on start Screen in MediaStore sample

### ISSUE THREAD

**Issue by chihung93** [android/storage-samples#48]
`2020-03-22 19:34:53.585 23637-23637/com.android.samples.mediastore E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.samples.mediastore, PID: 23637
    java.lang.IllegalStateException: displayName must not be null
        at com.android.samples.mediastore.MainActivityViewModel$queryImages$2.invokeSuspend(MainActivityViewModel.kt:193)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)`

**Comment by volkansahin45** [comment]
Hey, I can't reproduce the problem. Do you still have crash? @chihung93

**Comment by chihung93** [comment]
> Hey, I can't reproduce the problem. Do you still have crash? @chihung93

Not anymore, thanks
