### ISSUE TITLE
Gray Gallery crash

### ISSUE THREAD

**Issue by zchrissirhcz** [android/storage-samples#64]
Hi Android Team

Thanks for sharing android examples projects.

I'm using Android 4.0.1 and opening this project:
https://github.com/android/storage-samples/tree/master/FileProvider

Without any modification, the generated apk on my Android 10.0 phone, started smoothly, but after selecting any existing image, or after taking photo using system camera, this "Gary Gallery" app just crash.

**Comment by cketti** [comment]
Stacktrace:
```
    java.lang.IndexOutOfBoundsException: 2
        at android.content.res.XmlBlock$Parser.getAttributeName(XmlBlock.java:207)
        at com.example.graygallery.ui.AppViewModelKt.getAttributesFromXmlNode(AppViewModel.kt:169)
        at com.example.graygallery.ui.AppViewModelKt.getImagesFolder(AppViewModel.kt:142)
        at com.example.graygallery.ui.AppViewModelKt.access$getImagesFolder(AppViewModel.kt:1)
        at com.example.graygallery.ui.AppViewModel$imagesFolder$2.invoke(AppViewModel.kt:56)
        at com.example.graygallery.ui.AppViewModel$imagesFolder$2.invoke(AppViewModel.kt:46)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.example.graygallery.ui.AppViewModel.getImagesFolder(Unknown Source:2)
        at com.example.graygallery.ui.AppViewModel.access$getImagesFolder$p(AppViewModel.kt:46)
        at com.example.graygallery.ui.AppViewModel$copyImageFromUri$1$1.invokeSuspend(AppViewModel.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by zchrissirhcz** [comment]
Thanks. Tested. Problem fixed.
